version: "3.9"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default: {}
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  nextjs:
    container_name: nextjs
    hostname: nextjs
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      default: {}


volumes:
  postgres_data:

networks:
  default:
    name: database
    attachable: true
