version: "3.9"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    networks:
      - net

  nextjs:
    container_name: nextjs
    hostname: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - net
    depends_on:
      - postgres

networks:
  net:
    driver: bridge
    external: true

volumes:
  postgres_data:
