version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
    restart: always
    networks:
      - net

  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - net
    depends_on:
      - postgres

networks:
  net:
    external: true

volumes:
  postgres_data:
