# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install Node.js dependencies
RUN npm ci

# Copy the rest of your application source code to the container
COPY prisma ./prisma

COPY .env .

RUN npx prisma generate
# RUN npx prisma db push


# Expose the port your application will run on
EXPOSE 3000

# Command to run your application (replace this with your actual start command)
CMD [ "npm", "run", "start" ]
